apiVersion: v1
kind: Service
metadata:
  name: {{ include "syslog-ng.fullname" . }}
  labels:
    {{- include "syslog-ng.labels" . | nindent 4 }}  
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if eq .Values.service.type "externalip" }}  
  {{- with .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 3 }}
  {{- end }}
  {{- else}}
  type: {{ .Values.service.type }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
{{- end }}
{{- if .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ .Values.service.loadBalancerClass }}
{{- end }}
{{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
{{- end }}
{{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}
  ports:
    - name: udp-port
      port: 514
      targetPort: 514
      protocol: UDP
    - name: tcp-port
      port: 601
      targetPort: 601
      protocol: TCP 
  selector:
    {{- include "syslog-ng.selectorLabels" . | nindent 4 }}
